### ISSUE TITLE
Create User Interface for the system - إنشاء واجهة المستخدم

### ISSUE THREAD

**Issue by SultanEid** [SultanEid/academicAdv-gp#1]
- As discussed in the report in the first semester: the UI must match what is in the report
- مثل ما تم مناقشته في الترم الأول, الواجهة يجب أن تكون مطابقة لما هو موجود في التقرير

**Comment by adeeel123** [comment]
The following user interface had been created and bound to the database

1- login interface
2-advisor interface
3-student interface
4-view student report
