### ISSUE TITLE
Database initialization - تهيئة قاعدة البيانات 

### ISSUE THREAD

**Issue by SultanEid** [SultanEid/academicAdv-gp#2]
- Must create a database 'scheme' on MySQL (or any alternative tool) 
- make sure that the table represents what is in the report and is compatible with the Class diagram model
- تصميم قاعدة البيانات على أدوات مثل MySQL 
- مطابقة الجداول للتقرير و التصميم الموجود للكلاسات

**Comment by adeeel123** [comment]
We have created MySQL database, and we had to preprocess the tables in order to match the class diagrm. The database is now bound to the UI
